FROM python:3.12-slim

# Install uv.
COPY --from=ghcr.io/astral-sh/uv:latest /uv /uvx /bin/

# Copy the application into the container.
COPY sre_agent/servers/prompt_server /app
COPY pyproject.toml /app
COPY uv.lock /app
COPY README.md /app

# Install the application dependencies.
WORKDIR /app
RUN uv sync --frozen --no-cache --no-dev --group mcp

# Run the application.
CMD ["/app/.venv/bin/mcp", "run", "server.py", "--transport", "sse"]
